stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: 36_kuda_ugodno_backend_api-app
  VPS_USER: mer1d1an
  VPS_HOST: 176.108.253.5
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY        # Добавьте SSH-ключ в переменные GitLab CI/CD

before_script:
  - echo "$SSH_PRIVATE_KEY" > private_key
  - chmod 600 private_key
  - eval $(ssh-agent -s)
  - ssh-add private_key

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker-compose -f docker-compose.yaml up -d --build
  only:
    - develop

deploy:
  stage: deploy
  script:
    - ssh $VPS_USER@$VPS_HOST "cd /home/mer1d1an/ && docker-compose down && docker-compose up -d"
  only:
    - develop