import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/entities/**/*.{js,ts,jsx,tsx,mdx}',
    './src/widgets/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
    colors: {
      transparent: 'transparent',
      white: 'var(--white)',
      'white-secondary': 'var(--white-secondary)',
      black: 'var(--black)',
      'grey-50': 'var(--grey-50)',
      'grey-100': 'var(--grey-100)',
      'grey-200': 'var(--grey-200)',
      'grey-300': 'var(--grey-300)',
      'grey-400': 'var(--grey-400)',
      'grey-500': 'var(--grey-500)',
      'grey-600': 'var(--grey-600)',
      'grey-700': 'var(--grey-700)',
      'grey-800': 'var(--grey-800)',
      'grey-900': 'var(--grey-900)',
      'grey-950': 'var(--grey-950)',
      'grey-primary': 'var(--grey-primary)',
      'grey-secondary': 'var(--grey-secondary)',
      'grey-opacity': 'var(--grey-opacity)',
      'green-primary': 'var(--green-primary)',
      'green-secondary': 'var(--green-secondary)',
      'green-tetriary': 'var(--green-tetriary)',
      'green-bold': 'var(--green-bold)',
      'green-50': 'var(--green-50)',
      'green-100': 'var(--green-100)',
      'green-200': 'var(--green-200)',
      'green-300': 'var(--green-300)',
      'green-400': 'var(--green-400)',
      'green-500': 'var(--green-500)',
      'green-600': 'var(--green-600)',
      'green-700': 'var(--green-700)',
      'green-800': 'var(--green-800)',
      'green-900': 'var(--green-900)',
      'green-950': 'var(--green-950)',
      'blue-disabled': 'var(--blue-disabled)',
      'blue-extra-light': 'var(--blue-extra-light)',
      'blue-light': 'var(--blue-light)',
      'blue-primary': 'var(--blue-primary)',
      'blue-secondary': 'var(--blue-secondary)',
      'blue-tetriary': 'var(--blue-tetriary)',
      'blue-50': 'var(--blue-50)',
      'blue-100': 'var(--blue-100)',
      'blue-200': 'var(--blue-200)',
      'blue-300': 'var(--blue-300)',
      'blue-400': 'var(--blue-400)',
      'blue-500': 'var(--blue-500)',
      'blue-600': 'var(--blue-600)',
      'blue-700': 'var(--blue-700)',
      'blue-800': 'var(--blue-800)',
      'blue-900': 'var(--blue-900)',
      'blue-950': 'var(--blue-950)',
      'blue-bold': 'var(--blue-bold)',
      'red-primary': 'var(--red-primary)',
      'red-primary-400': 'var(--red-primary-400)',
      'red-primary-800': 'var(--red-primary-800)',
      'red-secondary': 'var(--red-secondary)',
      'yellow-primary': 'var(--yellow-primary)',
    },
    container: {
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
      center: true,
    },
  },
  variants: {
    extend: {
      backgroundColor: ['hover', 'active', 'disabled'],
      cursor: ['disabled'],
    },
  },
  plugins: [],
} satisfies Config;
