export const airports = [
  { code: 'SU', name: 'Аэрофлот' },
  { code: 'SF', name: 'S7' },
  { code: 'DP', name: 'Победа' },
  { code: 'UG', name: 'Уральские авиалинии' },
  { code: 'FV', name: 'Россия' },
  { code: 'UT', name: 'UTair' },
  { code: 'NL', name: 'Северный ветер' },
  { code: 'WZ', name: 'Red Wings' },
  { code: 'YC', name: 'Ямал' },
  { code: 'JW', name: 'Azur Air' },
  { code: 'BB', name: 'Белавиа' },
  { code: 'TK', name: 'Turkish airlines' },
  { code: 'EK', name: 'Emirates' },
  { code: 'OS', name: 'Qatar Airways' },
  { code: 'LH', name: 'Азимут' },
  { code: 'IQ', name: 'Pegasus Airlines' },
  { code: 'YK', name: 'Corendon Airlines' },
  { code: 'HY', name: 'Air Arabia' },
  { code: '5N', name: 'Fly Dubai' },
  { code: 'CC', name: 'China Southern Airlines' },
  { code: 'CI', name: 'China Eastern' },
  { code: 'SA', name: 'Sichuan Airlines' },
];
