export const flightData = {
  flights: [
    {
      id: 1,
      flight_number: 'AA101',
      airline: 'Air Arabia',
      departure_airport: 'Москва, Домодедово, DME',
      arrival_airport: 'Найроби, Джомо Кеньятта, NBO',
      departure_date: '2025-03-22',
      departure_time: '00:20',
      arrival_date: '2025-03-22',
      arrival_time: '13:15',
      price: '1000 USD',
      service_class: 'Без богажа',
      flight_type: 'Ручная кладь 1x10кг',
      description: 'Перелет Москва — Найроби, 12ч 55м в пути',
    },
    {
      id: 2,
      flight_number: 'AA102',
      airline: 'Air Arabia',
      departure_airport: 'Найроби, Джомо Кеньятта, NBO',
      arrival_airport: 'Москва, Домодедово, DME',
      departure_date: '2025-04-01',
      departure_time: '14:02',
      arrival_date: '2025-04-01',
      arrival_time: '02:10',
      price: '1000 USD',
      service_class: 'Без богажа',
      flight_type: 'Ручная кладь 1x10кг',
      description: 'Перелет Найроби — Москва, 12ч 5м в пути',
    },
  ],
};
